// Login

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const LOGOUT_USER = "LOGOUT_USER";

// Dashboard //

export const PERFORMANCE_LIST_GET = "PERFORMANCE_LIST_GET";
export const PERFORMANCE_LIST_GET_SUCCESS = "PERFORMANCE_LIST_GET_SUCCESS";
export const PERFORMANCE_LIST_GET_ERROR = "PERFORMANCE_LIST_GET_ERROR";

export const CALLS_LIST_GET = "CALLS_LIST_GET";
export const CALLS_LIST_GET_SUCCESS = "CALLS_LIST_GET_SUCCESS";
export const CALLS_LIST_GET_ERROR = "CALLS_LIST_GET_ERROR";

export const ENGAGEMENT_RATE = "ENGAGEMENT_RATE";
export const ENGAGEMENT_RATE_SUCCESS = "ENGAGEMENT_RATE_SUCCESS";
export const ENGAGEMENT_RATE_ERROR = "ENGAGEMENT_RATE_ERROR";

export const MEETINGS_LIST_GET = "MEETINGS_LIST_GET";
export const MEETINGS_LIST_GET_SUCCESS = "MEETINGS_LIST_GET_SUCCESS";
export const MEETINGS_LIST_GET_ERROR = "MEETINGS_LIST_GET_ERROR";

export const TEAM_LIST_ADD_MEMBER = "TEAM_LIST_ADD_MEMBER";
export const TEAM_LIST_ADD_MEMBER_SUCCESS = "TEAM_LIST_ADD_MEMBER_SUCCESS";
export const TEAM_LIST_ADD_MEMBER_ERROR = "TEAM_LIST_ADD_MEMBER_ERROR";
/* SETTINGS */

export const CHANGE_LOCALE = "CHANGE_LOCALE";
export const DARK_MODE = "DARK_MODE";
export const WHITE_MODE = "WHITE_MODE";

export * from "./settings/actions";
export * from "./auth/actions";
export * from "./app/dashboard/actions";
